### ISSUE TITLE
Do we still need 2000 image if each image contains ~96 marker areas?

### ISSUE THREAD

**Issue by DLMLPYRTRAINING** [AlexeyAB/Yolo_mark#100]
Hi Alexey/Team,

A small doubt.

I am trying to detect a plate with 96(8 rows X 12 column) wells in it.
So I have 2 class (With liquid & Empty) & 24 images total out of which 12 images have 96 marked square for the class empty and other 12 image have 96 marked square for the class "with liquid".

Now, I have read the general rule of thumb is that we need ~2000 images/class and 2000 iteration/class for the good enough training.

So, my question is, 
1. will it be ok if I have 96(for easier math lets say 100) object marked per image, do I still need 2000 image?
2. When we say we need 2000 image/class, are we actually looking for 2000 marked areas/class or 2000 actual separate image irrespective of how many ever classes are there in each of the images.
3. Apart from accuracy does having more images have any other benefit? let's say does it speed up the process and let us reach higher Avg IOU "faster"?
4. Given the scenario I have described above: 2 class/24 image with 96 object per image for 12 image for each class.

This is the current run state: 
`303: 215.209045, 246.505692 avg loss, 0.000008 rate, 303.448941 seconds, 19392 images
Loaded: 0.000041 seconds
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.376002, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: 0.545422, Class: 0.500651, Obj: 0.200670, No Obj: 0.194325, .5R: 0.675852, .75R: 0.028320,  count: 2613
Region 16 Avg IOU: 0.400653, Class: 0.499860, Obj: 0.376553, No Obj: 0.376001, .5R: 0.333333, .75R: 0.000000,  count: 6
Region 23 Avg IOU: 0.536507, Class: 0.500240, Obj: 0.200680, No Obj: 0.194321, .5R: 0.653323, .75R: 0.037311,  count: 2573`

Am I doing fine? Do you recommend changing anything?
5. The system I am using 1 small GPU (1 gb) with CUDA 7.5(I bet you will laugh) but i was wondering what is the systems you guys personally use, what Graphics card and all? Just wanna know to put things into perspective.

Thanks for your time and help with the questions.
Sandeep

**Comment by AlexeyAB** [comment]
@DLMLPYRTRAINING Hi,

1. If there are all types of objects in these 24 images and your training dataset includes images with objects at diffrent: **rotations**, from **different sides, on different backgrounds** - which will be in the Test images, then I think 24 images x 100 objects will be enough.
    But if you don't have enought backgrounds, then you should add images with backgrounds.

2. Actually we are looking for 2000 images instead of 20 images x 100 objects. Because:
    * usually all objects on the image have the same side, rotation and background, i.e. usually we can't have all rotations and all background on 24 images 
    * if we add 2000 images (negative samples), then we will have 20 images with objects and 2000 images without object, then it can bring imbalance.

3. More images in Training dataset - you should train more iterations and you will get higher mAP and IoU on the same Test dataset

4. Your training goes well. Check that you set `batch=64` (if it causes an error, then set batch=64 subdivisions=64)

5. I use GTX 970 for tests and Quadro P5000 (~GeForce Titan 1080) for long Training. Currently better to buy and use GeForce RTX 2070 then you can train with `GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1` in the Makefile after 2000 iterations with amazing speed. But you can use some 1 GB GeForce. I only will laugh if you will use CPU for training )

6. Also you should set `max=100` in the each `[yolo]`-layer, because there is limit of objects on 1 image `90` by default: https://github.com/AlexeyAB/darknet/blob/25f65f6878f713a7d0b7faabe94a7564d9a1ec08/src/parser.c#L278

**Comment by DLMLPYRTRAINING** [comment]
Thanks a bunch for explanation Alexey.
I'll follow though the guidance.
