### ISSUE TITLE
Images are stretching and unable to tag properly 

### ISSUE THREAD

**Issue by dexception** [AlexeyAB/Yolo_mark#139]
Images are of size 50x500

And it is getting very difficult to tag small items like hat, watch and shoes. 
Is there an option to see the image as it is ?

**Comment by dexception** [comment]
@AlexeyAB 
Can you help me on this issue on priority ?
Thanks.

**Comment by Fireye025** [comment]
I had the same problem, if your image has a square size go on line 467 and put `Mat full_image(Size(1280, 1280), CV_8UC3);` instead of the actual line, now your image should looks better.
Dont forget to make again.
I think it would be possible to find the image size and to adapt the code but I did that for the moment and I only have square pictures.

**Comment by dexception** [comment]
I am actually fed up with yolo_mark so have completely moved to labelimg.
