### ISSUE TITLE
how to create a video gui

### ISSUE THREAD

**Issue by xxccry** [AlexeyAB/Yolo_mark#16]
Hi @AlexeyAB , this project is so cool. Can you supply a video Gui for Yolo_mark? That is soooooooo cool, and this video is captured from webcam. I this is a great real-time detection project. I try it many times, but fail it, can you help me? 
Good Luck.
Cheers

xiaochuan

**Comment by AlexeyAB** [comment]
Hi @xxccry 
What do you mean by the video-GUI?
* Do you want to use one videofile instead of many imagefiles as source for Yolo_mark? To mark labels for each 25 frame on the video - i.e. pass videofile to Yolo_mark, select labels and get as output many imagefiles with labels.
* Or do you want video guide - how to use Yolo_mark?

**Comment by xxccry** [comment]
HI @AlexeyAB 
Thank you for your replying. I want to use webcam instead of one videofile, I try it many times, but fail. This Yolo_mark is good. I use the original project yolo and find it is so slow, I think your project yolo_mark is much more fast? So I want to use your project, and use the webcam to capture our videos. Do you understand my meanings? Thank you very much.

**Comment by AlexeyAB** [comment]
This repo for labeling images for Yolo v2 to train for detection your own objects. It isn't for capture videos.
