### ISSUE TITLE
getting nan value while training

### ISSUE THREAD

**Issue by anjuasadel** [AlexeyAB/Yolo_mark#29]
when i'm trying to train my dataset on yolo it's giving me some nan value.
I have 200 images of dataset. and I want to train my network so that I could get weights for my model.

please help me resolving this error.
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.469436, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.461745, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.463417, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.463578, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.464747, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.465984, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.463966, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.463675, Avg Recall: -nan,  count: 0
1: 217.337524, 217.337524 avg, 0.000500 rate, 1.763889 seconds, 16 images
Loaded: 0.000051 seconds

**Comment by AlexeyAB** [comment]
* What repo do you use this https://github.com/AlexeyAB/darknet or this https://github.com/pjreddie/darknet ?
* What cfg file do you use as base for your cfg-file: yolo-voc.2.0.cfg or yolo-voc.cfg?
* How did you get your training dataset, what software did you use to get labels?
* Do you have values of x,y,w,h <= 0 or >=1 in your leabel txt-files?

**Comment by anjuasadel** [comment]
1.I have used this
https://github.com/pjreddie/darknet ?
2. yolo-voc.2.0.cfg
3. bbox label tool
4. my some of the text files are as follows: : 
0 0.630078125 0.51875 0.041406250000000006 0.23958333333333334
0 0.5769531250000001 0.4791666666666667 0.03671875 0.16458333333333333

**Comment by AlexeyAB** [comment]
If you used bbox-label-tool instead of Yolo_mark, then you should check each your txt-file, and check that none of the objects are outside the screen, i.e. none values >= 1 or values =< 0

**Comment by anjuasadel** [comment]
yeah, i have cross checked the same.
none of the txt file contain value lesser then 0 and greater then 1.

**Comment by AlexeyAB** [comment]
Try to add the parameter `small_object=1` in the last layer `[region]` in your cfg-file: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection
And try to train using this fork: https://github.com/AlexeyAB/darknet

**Comment by inders** [comment]
I am facing the same while the darknet repo on VOC dataset. What's the resolution here guys?

**Comment by Luxato** [comment]
@inders are you using the https://github.com/AlexeyAB/darknet fork and did you put small_object=1 into your cfg file as mentioned above?

**Comment by kpreeti096** [comment]
when i'm trying to train my dataset on yolo it's giving me some nan value.
I have 60 images of dataset. and I want to train my network so that I could get weights for my model.45: 14.083967, 18.795122 avg, 0.000000 rate, 177.142862 seconds, 360 images
Loaded: 0.000055 seconds
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.500224, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.498702, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.501422, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.501599, Avg Recall: -nan,  count: 0

I am also getting the same issue.
1. I have used   https://github.com/AlexeyAB/darknet 
2. yolo-obj.cfg
3. bbox label tool
4.I don't  have values of x,y,w,h <= 0 or >=1 in my leabel txt-files

Suggest me if anyone have the idea to deal with this issue

**Comment by AlexeyAB** [comment]
@skyuuka It is normal. Your training goes well.
